name: question_game
description: Question entertainment game project for DAPI.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: any

  cupertino_icons: any
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_launcher_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_launcher_icons:
  image_path_android: "assets/image/app_icon.png"
  android: true
  web:
    generate: true
    image_path: "assets/image/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"



  # To add custom font to your application, add a font section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "font" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # font:
  #   - family: Schyler
  #     font:
  #       - asset: font/Schyler-Regular.ttf
  #       - asset: font/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     font:
  #       - asset: font/TrajanPro.ttf
  #       - asset: font/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding font from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
